apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: netbird
spec:
  forProvider:
    name: Netbird
    accessType: PUBLIC
    clientId: netbird
    description: Netbird Client
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    oauth2DeviceAuthorizationGrantEnabled: true
    baseUrl: "https://netbird.stonegarden.iseja.net"
    validRedirectUris:
      - "http://localhost:53000"
      - "https://netbird.stonegarden.iseja.net/*"
    validPostLogoutRedirectUris:
      - "https://netbird.stonegarden.iseja.net/*"
    webOrigins:
      - "+"
    realmIdRef:
      name: homelab
