---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: users
  namespace: dns
spec:
  encryptedData:
    users.yaml: AgAL9kYfx3EYs4RrYWTpZbQ0jKSCvSTDkaVXls/Sbl2QVeQoYmNt42syzIEnvUsxTNyeZU27UdsZa3ujFNPqcZjoWDhva31cUqGkkzcBUQkBbMgrLsPQgqxbAfVfLtU4FM6ERJMLKYvoBSNlmSRHZDnNAn6Lr0/Cijff1hbPUtGlHDtGZwANGJCqFL0gy+1RDIjojB+amNsxuyVXSCkh8nmmMdxP2ZQwMciwkB/Ga1D83+rU8No3uzdxWe/6pGgGaFi51JC+tu6PO1BtBuvvqaYAGPEN4VE9/Q5+NGYc4ZB/lmpkc7LrNogog85UJ7iiSTsoG9MRwBy9uOlehTyZK7Wom0L3qFbirmXikmMcoTR5Mqqm/UxPuR5U6/0ZFg8Y+yaeINrhqy0xM/D0PZvL92WLY+oUNMHbFpAGsuc0mGYHk6vCorsiS1wBWPy6dVyIR5YdlFQQmK3ThlXW8497YO4fhznwXNa4Bm8VpUcVapqyrr4CbTV6iPtTdIhX9jJv9T4o5TJWZ531v6HJgjS8hBQ9dP8LOMCtzxAjbcre63GKfaZRIUtt60qA3YplXPN2bd1bHQ0FVsrqzm5GOvbDHxpGDRX6HRrnyX7dug9kS7p4M7mtqygKWZ6XX2ezhynrKd+kMEEuzUZhxzwF0VNfHNfqk3hjGJhLdQpD7oR5fPcSz7aiV4vBuzz3sRGKfwbsEasEG32iD3FRheOSAGqXPxlalAQtVxD0c06hTzL5SejPqqzUkeEQ85WagkWyGAsfWfr22fxSluTNWSUW2AV1o2XrGNMqhkF+CEDLDKrObWwWjwpitsUxO2BHfYbHxjszV+EF5W+A3OM=
  template:
    metadata:
      creationTimestamp: null
      name: users
      namespace: dns
