apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: first-pool
spec:
  blocks:
  # 10.7.4.224/28 = .224 - .239
    - start: 10.7.4.224
      stop: 10.7.4.239
    - start: 10.7.4.20
      stop: 10.7.4.29
    - start: 10.7.8.20
      stop: 10.7.8.29