apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCDBhs4NxPSat4lEzUYDGZ7/auF8en4pVkVzFYae/I6Oc7ztmC/p3WXEIFEzKu1UyVLVhvsP1VWGN3SJOfRYXflDYMtZTY16vbt6JBfyM+xt00RIDbuYWZyPMulX6XtqWa5BnXHMAkCUX0hcp7qSNCldenNOtlJmbBoy6cMGdlyU6ttea0NDgYPn523ZnYRhEXG8b2OJfvg+d1ufpRiiPfRQRq9jYxmu20T14W+W/jnizr9GN1d5TuptG/JxXjRFe0DHf9zql8Ownst4Gtb10O61NsDac9F9gOHZZDhSs0zOkFna1yLZg+QPxTxKPUtA3fXq2Y0+bBYvVfArTkc6wOpppDVafHNmDB31rbQZdlNxCDMRxuWN+dmFTQfzck4ntp56MeMsSn7hBecghLyyN6EtCK7RZ395ZABP0y8kNozkf+tfWaENOsWEAT2YErWt8ruBgfpkwLG8x3j6VcgAmYOvAtsc6NjNnu8ZZgr5UnPH8uZUD0ULkpT/fwXJEO9wVdiM1XKxedCeQIAiWkezQPXpzF5Sg7v62/eqFA1bo7nkodTYD9pfbVv9gz0nWkmj0UMB1TEYmI26QFJgGgCxOxxnVmE4nHGG7MU68m/mniawoaf/bSvkg+yrkAknfNSbM5SJ8Qq6h5IsutMVRqHy1UpFqZPeJzJORHN+rFlj18zzPiIxQDq+NtK68qMDnF7GdXp2aRN5+fTlx5lWN6/kh/9jzU0dYJXiXhNadv1IhqDY4I9kScxaeUGtXWmwT6j6B1KSpiIeZSEVObEf9YpjDMRkGiC6RBZY0hktbOL2Ixraxn7z1eKLYSSg2bgjncn9FS3OOYoTdZRVttYqqLV2KK4o0ZgvCwGm1edr8S2xX6nUbz/CH7alGbtedpXM2DwjvWd25NvPxkykXgQ6QgKibazHRpKjn8eycY4QPyI5CFsUuPRVK5AHPom
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
