---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBAauJ9IVtn3STgyhASQ6/vqNCLGqnzz5+/Nrc6wVmdEzzeX7NZiRSZv1ZpNKOyLmPsioejpNAbj51m61/LzkXGvcH2/LVkwYASin/EPH0ER98qTAlrwa5kHF/7sijLLpG8oFIiJD86s0wn7NzoBfs6vqz6wLAEafcPME9T8lP2Z4Ll/MbVc7ff796iQn88rD8+yXZ4XUviBgtzrINVqMqRZA/8n04KCr2to8JCJ6Ybnf7VKz1/H11PnrUaDJuc5WAKIXtFskKFOinNpXU+s51nzYIFZJRzlzL1xYWCYKRuUAo4/Wg5h8vDxqIicWait1xHWUJYhQfDMYzKvg24BJjsWm4n1OukGfX3pdKjIqkRJev/YifBZBAM2JHiRj1jXk5hJk5De0lD1hVq88d1NRUPrAIHIxZyA9HKwy33YRhnZHF3jmrVzNnFehXzy2X1KNxK0ClHFRfpnXDfG2FGZ9gHAst6OSn6C4xwfnw45RMDoEEhctb6iIUMrBeo+F5eWdD45D9Iw5IB5rmy0SSNyJOAmtjWj4K7OKGhJmkmy9/m6UPFNUsj8BXMT3vGhWnrUHKc+E8PCdatOb/GxqJBFYjm9qsI6g+BuLi5mOSHJ/HxUUttlcSiQvFAz3g2xdjiJnmybOQs0iygNptXyLYxB3ykdmPnzIWTl4icPFv2EgM8EVrUaQNgqLFfXH0PGQLg89Jwg5JWYPsdn27MtoefgnhTtCHs88nstMwjYBuhw2e8RV7WGc8YNkkbSabz5aQdLIDlu8AZ23kwkFFIZ3T+H+l6ZYr6w64EBke/M3uBwiGurGlDo2NLcARR2xd95+/19L/35J/kxAipCyaQE/te4tSi0P/13JZVNsvFXU++46RO3TqFRpjYpNRpy0cN8lbiwRmSbYysH5Tr92cL/8e99ycMtropr8s77aHgQFBZtYenb0JGGKyXuuSTmsx1h45YjDUo4hPU5PWOXPkHUl55JaTYmal12eMUsiiuIMvwn8ae7t7fkDZvgMn4ohzFzVnP9pNozLTTpwoje/zME5IwZY1AQtCMvS6ryKEKp1FF/LF5KgZdLDE+vYYXapv6uzNEFpi6dID1080T2uHBrLCUCQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
