---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAAxW78Yepb5jZgRM7PiAzm7kv/cOngXAjHUwqEQxdZZ8QE2D8cC2FQyROcBezRQiwJaXBe8N1thAbAh3rzP/GCfbKBsN0WymSeIMQ/0czv8WfWR0PlmQ+n5YtOJJpZnlZ1gA1k6Ivp2LwtE+3QIQtFXOmDYDBCT7WXp0lE5UQkrTBBZ7zq+KH+YHzGVD4+fr34vfvb4jb4NScHU/ZT2KOlkUfwl50xv8o35mNln/jCuv2cb+tKwEuSN3qDJ6FBaFv2Tiz0XtzGYHL/uzuk8Vnb5ME+e0RfBLwwe0Y6bnkXbAENk6SUSEPOpVmdekKic5wxQYR+toUKJh3oWg1x0rLXGZy5gOZvEUp1xx+/CmMz2rgtyO37iKBMfY8phxRO8UFOZ1x9USrf2BiZtN7U/JlJsdAGY7Ixp8STDHFmxOQsHsXXyL7zfpUOA5NoDcexXYa+aFnE/NAZHJHjA6mm7qlAYoHnzIDiEGAq7JGeHFmID95M50jSrv5jAWTtwZ3HBNcTpG9KpxkhqzK0/LFb3xvrnx/W9McZ4Mr1jWKg7BV/jiJX7hm5nNaldoBME/iB/nbES70bpiX2EHvLn7SIGkNW9jkRbKLqTzZrLyDIElURR8u6J/JI4gdpyYtqjtieqLUq+HZxHkvro8fmfTecZMdPUyfoi4WYa1tjpnFMD3naLAMIELpXI/EvUTK7w4/u4UEMemjM4ihM+OCCPwimHDyvGUXaDDgxOJtbXFWwb26Smx3jmUrXtMRNtHOZlnfcaCu/5LovzHPA/0Jh/uSFAC2WjmHU92Rwq+KbACH9lH3Qf93zQ9VEyRd9wyBki1uJKDguK5/9rScMmbrIixxLWiQyJQ+FtI8XTiOczFvKR9GWJb3tVW9lit6nuyyoneSBVJ/lDDBsLiXEYUCfdQcz9Di7ww==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
