---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAwIgqOonswx5BcBwMbbqJ1zuItGXnM33GEynAFVfOcX1E2sEwo+XSRgr6xq1LuQxRGg/B8yE+fjsdP3jux1Ndla+3tg6CGrsFGkHtSJr9fjdMiG688wuJ17hwj/VM9n/glJp5yQ+k/TsB5s51qsFFNFzGhBU6unTm15dgQLRD/q3mDj/V7XjeOBDolqmnqIPDt6A5BlxDpcHun4iC9gS1TQhfqqBEJIn134Nty7hkzSUzkZ2Ewy/RapMN///r6x5YPhb12SQDWi5sgecmTTZ7aKWsyRDBiRZZtus4bx7Wttg+8V2XM+2c4M+ZGJMj7xiZK/8cb750SSRdq5gNFar4pNx4dK9Nb3TqazUz+sTjEiO8FKWL11R4PIoO6JEuAZe3Bgvs1xlymuEgBV8Ar26iPZEpZ95ZvFygyBos7S0iHTZOaEEljupMwKY/NTjDk48KK7+XT3YIGLwoM4vW4HtwMt+1QbxwsL3FOhtYOxCbpXD6bDjnk5xVrjwoMKcfMfk8lh7/xVa93zvzU1MGvE30snDmawsQIB8Xd+2ESjCt6oLW1BKnDHLAByiAliT/pr8WYG8Byqa1DEs5D5JUPnSQ2nmwGtwEEjqz1fcdUIJ25nuoCdnDVNy3+rgexW9GUiVE1juzXGltKy9WF3+9KD7e62Yml97NJO/Ur6DALmOydmsGyAEElTSEICBWqION6NaDyU49b8RIAWwLX5L38evTx3ZIlm/jKxFusqTR2s8vAPqgmV8/JwCsAukh0boEVy86BYuupHrOsTHFgIuTV6tEwRrZjqItoSOXvpEnlymzdtfayoWLX3/x4LxQXwOt5eqU6UydIi95vMVYosMSvY4dkjh8gdQcH3Fre4CkgCi41Glke0SYoifQt3GlNRH8A27E2+SH7F/NfuMpnufqEvAcM2g==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
