apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-stonegarden
  namespace: gateway
spec:
  dnsNames:
    - "*.stonegarden.iseja.net"
    - stonegarden.iseja.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-stonegarden
  usages:
    - digital signature
    - key encipherment
