apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: single-example
  namespace: cnpg-database
spec:
  instances: 1
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: euclid
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
      additional:
        - selectorType: rw
          updateStrategy: patch
          serviceTemplate:
            metadata:
              name: single-example-ext
              annotations:
                io.cilium/lb-ipam-ips: 10.7.4.230
            spec:
              type: LoadBalancer
  storage:
    size: 4G
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: pv-single-database
      accessModes:
        - ReadWriteOnce
