apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: single-example
  namespace: cnpg-database
spec:
  instances: 1
  # https://cloudnative-pg.io/documentation/1.24/quickstart/
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  # https://cloudnative-pg.io/documentation/1.24/monitoring/
  monitoring:
    enablePodMonitor: true
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: euclid
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      secret:
        name: authelia
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
      additional:
        - selectorType: rw
          updateStrategy: patch
          serviceTemplate:
            metadata:
              name: single-example-ext
              annotations:
                io.cilium/lb-ipam-ips: 10.7.4.230
            spec:
              type: LoadBalancer
  storage:
    size: 4G
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: pv-single-database
      accessModes:
        - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia
type: kubernetes.io/basic-auth
stringData:
  username: 'authelia'
  password: 'authelia'
