apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCvGNqDEW82qmchlHO474zFJl2zELk/uQhsibdQAud5r7BOi1rJsQORE3I6h6J7CEM3huVAZMbxVOx/zRJhtuwNube950VoB6mUBivxc2H10BtDFhZQEX/hpacXb2hL7hBluYTQ4boI5uBFNd/8Z6dBdwbY6lsWJ/v9Xn+WsoOmeezVnIlnzN/8iJ0fBeCP97XW9I7zB7Fhr8vl7jdoz/wuCSn4CVCmvQOuEIKEXbft9AtBTOSI1JgAmLI2CngY4SKWppt4RZNSDrVX1lKaKGlWg0SrcYTU3wsAb+dOKJH7e+vfpgqyDhRoaFeN0Cs/S7xtPUv9fn/n8RKjN53t45R/+rLAy0EgGBzYiSP+yIykCZ04/obqvfVc0qbaTo/KsY8ZwEcz5h5s5bT5kekYrYQkDsgvtWGFWheoErbW3CXfdhGj/jdfhvYbhGjqiOYRqRib9vttfyy5Ri967h4DawW/ubip0GWau9cWELczCeQrv8MwGbgf7qUo8LQ+NJKqadudif7qUeEpj5Ri88nZAO2/dtcWNi1esWCDMz30OR/kq9DLCriCKrNc+t+qNnDOHHTNp+OtaqGkp0MLlnbLTciKrzzL3VJESpZ9cgSsoXady4Ka9vLqIEvYfRYVwsyIsdJE4kNu9ZyUS/SrM3p6t3N8b9QNIc9F058OvoiqFZqbecaN+npsZKyB0uPtM2552R2xF9F10TF4lxR0zxF9E58UrFck60M0lTZ1sRQ8T03HcVIBNh3b0YhK
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
