apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media
  namespace: argocd
  labels:
    dev.stonegarden: application
spec:
  generators:
    - git:
        repoURL: https://github.com/sebiklamar/vehagn-homelab
        revision: HEAD
        directories:
          - path: k8s/apps/media/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: media
      source:
        repoURL: https://github.com/sebiklamar/vehagn-homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true