apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/sebiklamar/vehagn-homelab'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'arr'
      server: '*'
    - namespace: 'plex'
      server: '*'
    - namespace: 'jellyfin'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'