apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: controllers
  namespace: argocd
  labels:
    dev.stonegarden: controllers
spec:
  generators:
    - git:
        repoURL: https://github.com/sebiklamar/vehagn-homelab
        revision: HEAD
        directories:
          - path: k8s/infra/controllers/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: controllers
    spec:
      project: controllers
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/sebiklamar/vehagn-homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
